import type { Metadata } from "next";
import { Atkinson_Hyperlegible_Mono} from "next/font/google";
import '@/styles/globals.scss'

const atkinsonMono = Atkinson_Hyperlegible_Mono({
  subsets: ["latin"],
  variable: "--font-atkinson-mono",
})


export const metadata: Metadata = {
  title: "No Zer0s",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${atkinsonMono.variable}`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
